Dropbox/Mi PC (LAPTOP-4A9P8DN5)/Desktop/ecommerce/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admins
  root to: "home#index"

  authenticate :admin do
    resources :products
    resources :categories
    resources :sizes
    resources :colors
    resources :variations
    resources :coupons

  end

  resource :cart, only: [:show, :update] do
    member do
      post :pay_with_paypal
      get  :process_paypal_payment
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Dropbox/Mi PC (LAPTOP-4A9P8DN5)/Desktop/ecommerce/app/models/coupon.rb
class Coupon < ApplicationRecord
  belongs_to :user

    #Método que permite definir mediante el type si puede ser usado por uno o varios usuarios
    def coupon_type?
      if type.eq?('target')
          return(count>0)
      end
    end
  
    #tipo de metodo a aplicar (dcto porcentual o monto) 
    def coupon_total_discount(total)
      if discount.eq?('percent')
        percent_value = amount.to_f /100
        total - (total * percent_value)
      else
        total = total - amount
        (total < 0) ? 0 : total
      end
    end
end

Dropbox/Mi PC (LAPTOP-4A9P8DN5)/Desktop/ecommerce/app/controllers/coupons_controller.rb
class CouponsController < ApplicationController
  before_action :set_coupon, only: %i[ show edit update destroy ]

  # GET /coupons or /coupons.json
  def index
    @coupons = Coupon.all
  end

  # GET /coupons/1 or /coupons/1.json
  def show
  end

  # GET /coupons/new
  def new
    @coupon = Coupon.new
  end

  # GET /coupons/1/edit
  def edit
  end

  # POST /coupons or /coupons.json
  def create
    @coupon = Coupon.new(coupon_params)

    respond_to do |format|
      if @coupon.save
        format.html { redirect_to @coupon, notice: "Coupon was successfully created." }
        format.json { render :show, status: :created, location: @coupon }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @coupon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coupons/1 or /coupons/1.json
  def update
    respond_to do |format|
      if @coupon.update(coupon_params)
        format.html { redirect_to @coupon, notice: "Coupon was successfully updated." }
        format.json { render :show, status: :ok, location: @coupon }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @coupon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coupons/1 or /coupons/1.json
  def destroy
    @coupon.destroy
    respond_to do |format|
      format.html { redirect_to coupons_url, notice: "Coupon was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coupon
      @coupon = Coupon.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def coupon_params
      params.require(:coupon).permit(:type, :code, :amount, :discount, :count, :user_id)
    end
end

Dropbox/Mi PC (LAPTOP-4A9P8DN5)/Desktop/ecommerce/app/helpers/coupons_helper.rb
module CouponsHelper
end

Dropbox/Mi PC (LAPTOP-4A9P8DN5)/Desktop/ecommerce/app/views/coupons/_form.html.erb
<%= form_with(model: coupon, local: true) do |form| %>
  <% if coupon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(coupon.errors.count, "error") %> prohibited this coupon from being saved:</h2>

      <ul>
      <% coupon.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :type %>
  </div>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.number_field :amount %>
  </div>

  <div class="field">
    <%= form.label :discount %>
    <%= form.text_field :discount %>
  </div>

  <div class="field">
    <%= form.label :count %>
    <%= form.number_field :count %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Dropbox/Mi PC (LAPTOP-4A9P8DN5)/Desktop/ecommerce/app/views/coupons/edit.html.erb
<h1>Editing Coupon</h1>

<%= render 'form', coupon: @coupon %>

<%= link_to 'Show', @coupon %> |
<%= link_to 'Back', coupons_path %>

Dropbox/Mi PC (LAPTOP-4A9P8DN5)/Desktop/ecommerce/app/views/coupons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Coupons</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>Code</th>
      <th>Amount</th>
      <th>Discount</th>
      <th>Count</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @coupons.each do |coupon| %>
      <tr>
        <td><%= coupon.type %></td>
        <td><%= coupon.code %></td>
        <td><%= coupon.amount %></td>
        <td><%= coupon.discount %></td>
        <td><%= coupon.count %></td>
        <td><%= coupon.user %></td>
        <td><%= link_to 'Show', coupon %></td>
        <td><%= link_to 'Edit', edit_coupon_path(coupon) %></td>
        <td><%= link_to 'Destroy', coupon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Coupon', new_coupon_path %>

Dropbox/Mi PC (LAPTOP-4A9P8DN5)/Desktop/ecommerce/app/views/coupons/new.html.erb
<h1>New Coupon</h1>

<%= render 'form', coupon: @coupon %>

<%= link_to 'Back', coupons_path %>

Dropbox/Mi PC (LAPTOP-4A9P8DN5)/Desktop/ecommerce/app/views/coupons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @coupon.type %>
</p>

<p>
  <strong>Code:</strong>
  <%= @coupon.code %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @coupon.amount %>
</p>

<p>
  <strong>Discount:</strong>
  <%= @coupon.discount %>
</p>

<p>
  <strong>Count:</strong>
  <%= @coupon.count %>
</p>

<p>
  <strong>User:</strong>
  <%= @coupon.user %>
</p>

<%= link_to 'Edit', edit_coupon_path(@coupon) %> |
<%= link_to 'Back', coupons_path %>